//import './globals.css'
/* import { Inter } from "next/font/google";
const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};*/
import Head from "next/head";
//import "./sass/style.scss";
import "@/sass/style.scss";
export default function RootLayout({ children }) {
  return (
    <html lang="da">
      <Head>
        <meta charSet="UTF-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1.0" />
      </Head>
      <head>
        <link rel="icon" href="/favicon.svg" type="image/svg+xml" sizes="any" />
      </head>
      <body>
        {/* navigation */}
        {children}
        {/* footer */}
      </body>
    </html>
  );
}
